name: Create new pull request

on:
  workflow_dispatch:
  issues:
    types: [ opened, edited, labeled ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9"]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Return issue number
        id: gh-script-issue
        uses: actions/github-script@v6.1.1
        with:
          # github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const issue_number = context.issue.number
            const repo = context.repo.owner+"/"+context.repo.repo
            return issue_number

      - name: Return label
        id: gh-script-label
        uses: actions/github-script@v6.1.1
        with:
          # github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const issue_label = "auto-pr"
            return issue_label
      
      - name: Return repository name
        id: gh-script-repo
        uses: actions/github-script@v6.1.1
        with:
          # github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const repo = context.repo.owner+"/"+context.repo.repo
            return repo

      - name: Set branch name
        id: vars
        run: |
          echo ::set-output name=branch-name::"ocrawl_automation"_${{ steps.gh-script-issue.outputs.result }}
          echo ::set-output name=resource::"src/ontology/go-edit.obo"
      # old resource = "tests/resources/fbbt.obo"
      #----------------------------------------------
      #          install & configure poetry
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1.3
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      #----------------------------------------------
      # install dependencies if cache does not exist 
      #----------------------------------------------
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
          poetry run pip install kgcl-schema

      - name: Run ocrawl
        id: ocrawl
        run: |
          echo ${{ secrets.GH_TOKEN }} >> /home/runner/work/go-ontology/go-ontology/.venv/lib/python3.9/site-packages/onto_crawler/token.txt
          poetry run ocrawl process-issue ${{ steps.vars.outputs.resource }} \
          -r ${{ steps.gh-script-repo.outputs.result }} \
          -n ${{ steps.gh-script-issue.outputs.result }} \
          -l ${{ steps.gh-script-label.outputs.result }}

      

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch-suffix: short-commit-hash
          labels: Automated
          body: ${{ steps.ocrawl.outputs.PR_BODY }}
          title: ${{ steps.ocrawl.outputs.PR_TITLE }}
          base: ${{ github.head_ref }}
          branch: ${{ steps.vars.outputs.branch-name }}